### ISSUE TITLE
Use Vue.js to add interactivity to the front-end/ TODO

### ISSUE THREAD

**Issue by edshen17** [edshen17/nikki#2]

**Comment by edshen17** [comment]
TODO-- Users should be able to:
- [x] Write their own posts
- [ ] Edit their own profiles 
- [x] View other posts
- [ ] Correct other posts
- [ ] Edit their own posts/comments
- [x] Comment on other posts
- [x] Like posts
- [ ] Follow others 
- [x]  Delete their own posts
